# Generated by Django 4.2.21 on 2025-05-23 17:58

from django.db import migrations, models
import subject_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(validators=[subject_app.validators.validate_professor_name]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(unique=True, validators=[subject_app.validators.validate_subject_format]),
        ),
    ]
